#!/bin/sh
set -eu
HOTBOX=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)


. $HOTBOX/lib/sh.sh


#
# Command-line arguments
#
system=false
while test $# -gt 0 ; do
    case $1 in
        --system)
            shift
            system=true
            ;;
        -*)
            die "Unrecognised option '$1'"
            ;;
        *)
            break
            ;;
    esac
done

test $# -gt 0 || die "Expected <feature>"
feature="$1" ; shift

test $# -eq 0 || die "Unexpected argument '$1'"


#
# User check
#
if $system ; then
    test "$(current_user)" = "root" || die "Must be root to set up system features"
else
    test "$(current_user)" != "root" || die "Must be unprivileged user to set up features"
fi


#
# Work out command to run
#
command="setup"
description="$feature"
if $system ; then
    command="system"
    description="system $feature"
fi


#
# Run it
#
features=${HOTBOX_SOURCES:-$HOTBOX/features}
$HOTBOX/lib/feature-command-exists $features $feature $command || exit 0
heading "Setting up $description"
$HOTBOX/lib/run-feature-command $features $feature $command
