#!/bin/sh
set -eu
HOTBOX=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)


. $HOTBOX/lib/sh.sh


#
# Command-line arguments
#
system=false
while test $# -gt 0 ; do
    case $1 in
        --system)
            shift
            system=true
            ;;
        -*)
            die "Unrecognised option '$1'"
            ;;
        *)
            break
            ;;
    esac
done

test $# -gt 0 || die "Expected <spec>"
spec="$1" ; shift

test $# -eq 0 || die "Unexpected argument '$1'"


#
# Read features from <spec>
#
features="$(cd $HOTBOX/specs && $HOTBOX/lib/read-spec $spec feature)"


#
# Set up features
#
system_switch=""
if $system ; then
    system_switch="--system"
fi
for feature in $features ; do
    $HOTBOX/hotbox-setup-feature $system_switch $feature
done
