#!/usr/bin/env sh
set -eu
HOTBOX=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)


. $HOTBOX/lib/sh.sh


early=false
while test $# -gt 0 ; do
    case $1 in
        --early)
            shift
            early=true
            ;;
        -*)
            die "Unrecognised option '$1'"
            ;;
        *)
            break
            ;;
    esac
done

test $# -gt 0 || die "Expected <spec>"
HOTBOX_SPEC="$1" ; shift

test $# -eq 0 || die "Unexpected argument '$1'"


#
# Read features from spec
#
. $HOTBOX/lib/source-spec.sh


#
# Set up features
#
if $early ; then
    test "$(current_user)" = "root" || die "Must be root to set up early features"

    for feature in $HOTBOX_FEATURES ; do
        test "${feature%%-*}" = "early" || continue

        heading "Setting up $feature"
        $HOTBOX/features/$feature
    done
else
    for feature in $HOTBOX_FEATURES ; do
        test "${feature%%-*}" != "early" || continue

        heading "Setting up $feature"
        $HOTBOX/features/$feature
    done
fi
