#!/usr/bin/env sh
set -eu
hotbox=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)


$hotbox/hotbox-build-alpine
$hotbox/hotbox-build-base hotbox-alpine hotbox-base-alpine
$hotbox/hotbox-build-dev hotbox-base-alpine hotbox-dev-alpine
