#!/bin/sh
set -eu
HOTBOX=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)


. $HOTBOX/lib/sh.sh


#
# Command-line arguments
#
system=false
while test $# -gt 0 ; do
    case $1 in
        --system)
            shift
            system=true
            ;;
        -*)
            die "Unrecognised option '$1'"
            ;;
        *)
            break
            ;;
    esac
done

test $# -gt 0 || die "Expected <feature>"
feature="$1" ; shift

test $# -eq 0 || die "Unexpected argument '$1'"


#
# Find script
#
feature_dir="$($HOTBOX/lib/find-feature $feature)"
test -n "$feature_dir" || die "Feature $feature not found"
feature_script_name="$feature.feature.sh"
feature_description="$feature"

if $system ; then
    test "$(current_user)" = "root" || die "Must be root to set up system features"
    feature_description="system $feature"
    feature_script_name="$feature.feature.sys.sh"
fi

feature_script="$feature_dir/$feature_script_name"
test -f $feature_script || exit 0


#
# Run script
#
heading "Setting up $feature_description"
env HOTBOX=$HOTBOX /bin/sh -eu $feature_script
