#!/bin/sh
set -eu ; set -o | grep -q pipefail && set -o pipefail
HOTBOX=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)


. $HOTBOX/lib/sh.sh
. $HOTBOX/lib/state.sh


#
# Command line arguments
#
extra_sources=
while test $# -gt 0 ; do
    case $1 in
        --source)
            shift
            test $# -gt 0 || die "Expected <source>"
            extra_sources="$extra_sources ${1%/}"
            shift
            ;;
        -*)
            die "Unrecognised option '$1'"
            ;;
        *)
            break
            ;;
    esac
done

test $# -gt 0 || die "Expected <spec>"
spec="$1" ; shift

test $# -eq 0 || die "Unexpected argument '$1'"


sources=$HOTBOX_STATE/sources/$spec.next
image="hotbox-$spec:next"


heading "Collecting hotbox specs and features"
echo_on
rm -rf $sources
mkdir -p $sources
cp $HOTBOX/specs/* $sources
cp $HOTBOX/features/* $sources
echo_off
for source in $extra_sources ; do
    test -d $source || continue
    echo_on
    cp $source/*.spec.sh $sources 2>/dev/null || true
    cp $source/*.feature.sh $sources 2>/dev/null || true
    echo_off
done


heading "Reading $spec hotbox spec"
features=$($HOTBOX/lib/read-spec $sources $spec feature)
features=$(echo $features)
baseimage=$($HOTBOX/lib/read-spec $sources $spec baseimage | tail -n 1 || checkpipe)
shell=$($HOTBOX/lib/read-spec $sources $spec shell | tail -n 1 || checkpipe)
shellarg=$($HOTBOX/lib/read-spec $sources $spec shellarg | tail -n 1 || checkpipe)
test -n "$baseimage" || die "No baseimage specified in $spec spec"
test -n "$shell" || die "No shell specified in $spec spec"


user="$(current_user)"
uid="$(current_uid)"
gid="$(current_gid)"
docker_gid="$(getent group docker | cut -d: -f3 || checkpipe)"


heading "Checking for existing $image container image"
echo_on
imageid="$(docker image ls -q $image)"
echo_off


if [ -n "$imageid" ] ; then
    heading "Deleting existing $image container image"
    echo_on
    docker image rm -f $image
    echo_off
fi


heading "Forking $image container image from $baseimage"
echo_on
echo "FROM $baseimage" | \
    docker build \
        --label hotbox \
        -t "$image" \
        - \
    || checkpipe
echo_off


hotbox_mount_options="$($HOTBOX/lib/run-feature-command $sources container-hotbox run)"


heading "Setting up system features in container"
echo_on
container=$(\
    docker create \
        --network host \
        --hostname hotbox-$spec \
        $hotbox_mount_options \
        --env HOTBOX_SOURCES=/hotbox-state/sources/$spec.next \
        --env HOTBOX_USER=$user \
        --env HOTBOX_UID=$uid \
        --env HOTBOX_GID=$gid \
        --env HOTBOX_DOCKER_GID=$docker_gid \
        --user root \
        --workdir /root \
        $image \
        /hotbox/hotbox-apply-spec --system $spec \
        )
docker start -ai $container
docker commit $container $image
echo_off


heading "Rebuilding /hotbox mount point in container"
echo_on
container=$(\
    docker create \
        --network host \
        --user root \
        --workdir /root \
        $image \
        /bin/sh -c "rm -rf /hotbox && mkdir /hotbox && chown $user:$user /hotbox && chmod 755 /hotbox" \
        )
docker start -ai $container
docker commit $container $image
echo_off


heading "Rebuilding /hotbox-state mount point in container"
echo_on
container=$(\
    docker create \
        --network host \
        --user root \
        --workdir /root \
        $image \
        /bin/sh -c "rm -rf /hotbox-state && mkdir /hotbox-state && chown $user:$user /hotbox-state && chmod 755 /hotbox-state" \
        )
docker start -ai $container
docker commit $container $image
echo_off


heading "Setting up features in container"
echo_on
container=$(\
    docker create \
        --network host \
        $hotbox_mount_options \
        --env HOTBOX_SOURCES=/hotbox-state/sources/$spec.next \
        --env HOTBOX_USER=$user \
        --env HOTBOX_UID=$uid \
        --env HOTBOX_GID=$gid \
        --env HOTBOX_DOCKER_GID=$docker_gid \
        --user $user \
        --workdir /home/$user \
        $image \
        /hotbox/hotbox-apply-spec $spec \
        )
docker start -ai $container
docker commit $container $image
echo_off


heading "Setting final container metadata"
echo_on
container=$(\
    docker create \
        --env HOTBOX_SOURCES= \
        --env HOTBOX_USER= \
        --env HOTBOX_UID= \
        --env HOTBOX_GID= \
        --env HOTBOX_DOCKER_GID= \
        --env HOTBOX_STATE= \
        --user $user \
        --workdir /home/$user \
        $image \
        /bin/sh -l \
        )
docker start -ai $container
docker commit $container $image
echo_off


heading "Committing final $spec container image"
echo_on
docker tag $image hotbox-$spec
rm -rf $HOTBOX_STATE/sources/$spec
mv $sources $HOTBOX_STATE/sources/$spec
docker image rm -f $image
echo_off


heading "Pruning orphaned hotbox containers and images"
echo_on
docker container prune -f --filter label=hotbox
docker image prune -f --filter label=hotbox
echo_off
