#!/usr/bin/env sh
set -eu
HOTBOX=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)


. $HOTBOX/lib/sh.sh


spec=""

if [ $# -gt 0 ] ; then
    if [ "$1" != "--" ] ; then
        spec="$1" ; shift
    fi
fi

if [ $# -gt 0 ] ; then
    if [ "$1" != "--" ] ; then
        name="$1" ; shift
    fi
fi

if [ $# -gt 0 ] ; then
    test "$1" = "--" || die "Unexpected argument '$1'"
    shift
fi

# Remaining arguments are <command> and <args> to run in container


spec="${spec:-alpine}"
name="${name:-$spec}"
image="hotbox-$spec"
image_id="$(docker image ls -q $image)"


if [ -z "$image_id" ] ; then
    $HOTBOX/hotbox-build $spec
fi


$HOTBOX/hotbox-run $spec $name $@
