#!/bin/sh
set -eu
HOTBOX=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)


. $HOTBOX/lib/sh.sh


#
# Command line arguments
#
volume_options=""
spec=""
while test $# -gt 0 ; do
    case $1 in
        --volume)
            shift
            test $# -gt 0 || die "Expected <volume>"
            volume_options="$volume_options --volume $1"
            shift
            ;;
        --)
            break
            ;;
        -*)
            die "Unrecognised option '$1'"
            ;;
        *)
            break
            ;;
    esac
done

if [ $# -gt 0 ] ; then
    if [ "$1" != "--" ] ; then
        spec="$1" ; shift
    fi
fi

if [ $# -gt 0 ] ; then
    if [ "$1" != "--" ] ; then
        name="$1" ; shift
    fi
fi

if [ $# -gt 0 ] ; then
    test "$1" = "--" || die "Unexpected argument '$1'"
    shift
fi

# Remaining arguments are <command> and <args> to run in container


#
# Find container image
#
spec="${spec:-alpine}"
name="${name:-$spec}"
image="hotbox-$spec"
image_id="$(docker image ls -q $image)"


#
# Build container image if necessary
#
if [ -z "$image_id" ] ; then
    $HOTBOX/hotbox-build $spec
fi


#
# Start or join container
#
$HOTBOX/hotbox-run \
    $volume_options \
    $spec $name \
    $@
