#!/usr/bin/env sh
set -eu
hotbox=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)


. $hotbox/lib/hotbox-alpine.sh
. $hotbox/lib/hotbox-base.sh
. $hotbox/lib/hotbox-docker.sh


hotbox_alpine_build
hotbox_base_build hotbox-alpine hotbox-base-alpine
hotbox_docker_run hotbox-base-alpine
