#!/bin/sh
set -eu ; set -o | grep -q pipefail && set -o pipefail
HOTBOX=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)


. "$HOTBOX/lib/sh.sh"


system=false
while test $# -gt 0 ; do
    case $1 in
        --system)
            shift
            system=true
            ;;
        -*)
            die "Unrecognised option '$1'"
            ;;
        *)
            break
            ;;
    esac
done

[ $# -gt 0 ] || die "Expected <spec>"
spec="$1" ; shift

[ $# -eq 0 ] || die "Unexpected argument '$1'"


target=machine
if "$HOTBOX/lib/in-container" ; then
    target=container
fi


features=$(echo $("$HOTBOX/lib/read-spec" "$spec" "$target" feature))


system_switch=""
if $system ; then
    system_switch="--system"
fi
for feature in $features ; do
    "$HOTBOX/hotbox-apply-feature" $system_switch "$feature"
done
