#!/bin/sh
set -eu ; set -o | grep -q pipefail && set -o pipefail
HOTBOX=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)
PATH="$HOTBOX:$HOTBOX/lib:$PATH"


. $HOTBOX/lib/sh.sh
. $HOTBOX/lib/state.sh


hotbox_images="$(docker image ls --filter label=hotbox -q)"


if [ -n "$hotbox_images" ] ; then
    heading "Deleting hotbox container images"
    echo_on
    docker image rm $hotbox_images
    echo_off
fi


heading "Pruning hotbox containers and images"
echo_on
docker container prune -f --filter label=hotbox
docker image prune -f --filter label=hotbox
echo_off


heading "Deleting container feature and spec snapshots"
sources=$HOTBOX_STATE/sources
echo_on
rm -rf $HOTBOX_STATE/sources/*
echo_off
