#!/usr/bin/env sh
set -eu
hotbox=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)


. $hotbox/lib/hotbox-ubuntu.sh
. $hotbox/lib/hotbox-base.sh
. $hotbox/lib/hotbox-docker.sh


hotbox_ubuntu_build
hotbox_base_build hotbox-ubuntu hotbox-base-ubuntu
hotbox_docker_run hotbox-base-ubuntu
