#!/bin/sh
set -eu ; set -o | grep -q pipefail && set -o pipefail
HOTBOX=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)
PATH="$HOTBOX:$HOTBOX/lib:$PATH"


. "$HOTBOX/lib/sh.sh"
export HOTBOX_TXN="$(hotbox-txn-begin $$)"
. "$HOTBOX/lib/hotbox-txn-end-on-exit.sh"


system=false
while [ $# -gt 0 ] ; do
    case $1 in
        --system)
            shift
            system=true
            ;;
        -*)
            die "Unrecognised option '$1'"
            ;;
        *)
            break
            ;;
    esac
done

[ $# -gt 0 ] || die "Expected <feature>"
feature="$1" ; shift

[ $# -eq 0 ] || die "Unexpected argument '$1'"


if $system ; then
    [ "$(current_user)" = "root" ] || die "Must be root to set up system features"
    command="system"
    description="system $feature"
else
    [ "$(current_user)" != "root" ] || die "Must be unprivileged user to set up user features"
    command="user"
    description="$feature"
fi


hotbox-feature-exists $feature || die "Feature $feature doesn't exist"
hotbox-feature-command-exists $feature $command || exit 0
heading "Setting up $description"
hotbox-feature-run-command $feature $command
