#!/bin/sh
set -eu
HOTBOX=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)


. $HOTBOX/lib/sh.sh


volume1=""
volume2=""
volume3=""
spec=""

while test $# -gt 0 ; do
    case $1 in
        --volume)
            shift
            test $# -gt 0 || die "Expected <volume>"
            if [ -z "$volume1" ] ; then
                volume1="$1"
            elif [ -z "$volume2" ] ; then
                volume2="$1"
            elif [ -z "$volume3" ] ; then
                volume3="$1"
            else
                die "Too many --volume's"
            fi
            shift
            ;;
        --)
            break
            ;;
        -*)
            die "Unrecognised option '$1'"
            ;;
        *)
            break
            ;;
    esac
done

if [ $# -gt 0 ] ; then
    if [ "$1" != "--" ] ; then
        spec="$1" ; shift
    fi
fi

if [ $# -gt 0 ] ; then
    if [ "$1" != "--" ] ; then
        name="$1" ; shift
    fi
fi

if [ $# -gt 0 ] ; then
    test "$1" = "--" || die "Unexpected argument '$1'"
    shift
fi

# Remaining arguments are <command> and <args> to run in container


spec="${spec:-alpine}"
name="${name:-$spec}"
image="hotbox-$spec"
image_id="$(docker image ls -q $image)"


if [ -z "$image_id" ] ; then
    $HOTBOX/hotbox-build $spec
fi


$HOTBOX/hotbox-run \
    ${volume1:+--volume} $volume1 \
    ${volume2:+--volume} $volume2 \
    ${volume3:+--volume} $volume3 \
    $spec $name \
    $@
