#!/bin/sh
set -eu ; set -o | grep -q pipefail && set -o pipefail
HOTBOX=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)
PATH="$HOTBOX:$HOTBOX/lib:$PATH"


. "$HOTBOX/lib/sh.sh"


container=false
system=false
while test $# -gt 0 ; do
    case $1 in
        --container)
            shift
            container=true
            ;;
        --system)
            shift
            system=true
            ;;
        -*)
            die "Unrecognised option '$1'"
            ;;
        *)
            break
            ;;
    esac
done

[ $# -gt 0 ] || die "Expected <spec>"
spec="$1" ; shift

[ $# -eq 0 ] || die "Unexpected argument '$1'"


features=$(echo $(hotbox-spec-read "$spec" feature))


system_switch=""
if $system ; then
    system_switch="--system"
fi
for feature in $features ; do
    case $feature in
        container-*)
            $container || continue;
            ;;
    esac
    "$HOTBOX/hotbox-feature-apply" $system_switch "$feature"
done
