#!/bin/sh
set -eu
scriptdir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)


. $scriptdir/lib/macro-sh.sh


cd $HOME


#
# Make sure there's a .gitconfig
#
if ! [ -f .gitconfig ] ; then
    info "No .gitconfig found, creating"
    touch .gitconfig
fi


#
# Make sure .gitconfig includes the macro-workstation gitconfig
#
if ! grep -qF 'conf/gitconfig' .gitconfig ; then
    info "No macro-workstation gitconfig include found in .gitconfig, prepending"
    cat .gitconfig > .gitconfig.old
    echo "[include]" > .gitconfig
    echo "	path = $scriptdir/conf/gitconfig" >> .gitconfig
    echo >> .gitconfig
    cat .gitconfig.old >> .gitconfig
    rm .gitconfig.old
fi


#
# Use totally insecure "store" credential store on Linux
#
if [ "$(uname)" = "Linux" ] ; then
    info "On Linux, using INSECURE store credential helper"
    echo_on
    git config --global credential.helper store
    echo_off
fi

