#!/usr/bin/env sh
set -eu
scriptdir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)


. $scriptdir/lib/macro-ubuntu.sh
. $scriptdir/lib/macro-base.sh
. $scriptdir/lib/macro-docker.sh


macro_ubuntu_build
macro_base_build macro-ubuntu
macro_docker_run macro-base
