#!/usr/bin/env sh
set -eu
scriptdir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)


. $scriptdir/lib/macro-ubuntu.sh
. $scriptdir/lib/macro-base.sh
. $scriptdir/lib/macro-dev.sh


macro_ubuntu_build
macro_base_build macro-ubuntu macro-base-ubuntu
macro_dev_build macro-base-ubuntu macro-dev-ubuntu
macro_dev_run macro-dev-ubuntu
