#!/usr/bin/env sh
set -eu
scriptdir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)


. $scriptdir/lib/macro-alpine.sh
. $scriptdir/lib/macro-base.sh
. $scriptdir/lib/macro-dev.sh


macro_alpine_build
macro_base_build macro-alpine macro-base-alpine
macro_dev_build macro-base-alpine macro-dev-alpine
macro_dev_run macro-dev-alpine
