#!/bin/sh
set -eu ; set -o | grep -q pipefail && set -o pipefail
HOTBOX=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)


. "$HOTBOX/lib/sources.sh"


feature="${1:?expected <feature>}"


[ -f "$HOTBOX_SOURCES/$feature.system.feature.sh" ] || \
[ -f "$HOTBOX_SOURCES/$feature.user.feature.sh" ] || \
[ -f "$HOTBOX_SOURCES/$feature.run.feature.sh" ]
