#!/bin/sh
set -eu ; set -o | grep -q pipefail && set -o pipefail
HOTBOX=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)


location="${1:?expected <location>}"
feature="${2:?expected <feature>}"
command="${3:?expected <command>}"


test -f $location/$feature.$command.feature.sh
