#!/bin/sh
set -eu ; set -o | grep -q pipefail && set -o pipefail
HOTBOX=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)


location="${1:?expected <location>}"
feature="${2:?expected <feature>}"


test -f $location/$feature.system.feature.sh \
    || test -f $location/$feature.user.feature.sh \
    || test -f $location/$feature.run.feature.sh
