#!/bin/sh
set -eu
HOTBOX=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)


spec="${1:?expected <spec>}"


for p in $($HOTBOX/lib/hotbox-paths) ; do
    if test -f $p/$spec.spec.sh ; then
        echo $p
        exit 0
    fi
done
