#!/bin/sh
set -eu ; set -o | grep -q pipefail && set -o pipefail
HOTBOX=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)


. $HOTBOX/lib/sh.sh
. $HOTBOX/lib/state.sh


test $# -gt 0 || die "Expected <url>"
url="$1" ; shift

test $# -eq 0 || die "Unexpected argument '$1'"


name="$url"
name="${name##*/}"
name="${name%.git}"
test -n "$name" || die "Couldn't determine git repo name from URL $url"


test ! -d $name || die "Git repo $name already exists"


#
# Create hotbox git cache
#
cache=$HOTBOX_STATE/git-cache
if [ ! -d $cache ] ; then
    echo_on
    mkdir -p $cache
    echo_off
fi


#
# Clone/fetch to the cache
#
if [ ! -d $cache/$name ] ; then
    echo_on
    git clone --bare "$url" $cache/$name
    echo_off
elif [ -n "${HOTBOX_REFRESH:-}" ] ; then
    echo_on
    git -C $cache/$name fetch
    echo_off
fi


#
# Clone from cache and set upstream origin
#
echo_on
git clone $cache/$name
git -C $name remote set-url origin "$url"
echo_off
