#!/bin/sh
set -eu ; set -o | grep -q pipefail && set -o pipefail
HOTBOX=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)
PATH="$HOTBOX:$HOTBOX/lib:$PATH"


. $HOTBOX/lib/sh.sh
export HOTBOX_STATE="$(hotbox-state-init)"


[ $# -gt 0 ] || die "Expected <url>"
url="$1" ; shift

filename=""
if [ $# -gt 0 ] ; then
    filename="$1" ; shift
fi

[ $# -eq 0 ] || die "Unexpected argument '$1'"

[ "$filename" ] || filename="${url##*/}"
[ "$filename" ] || die "No filename in <url> and no <filename> specified"


cache=$HOTBOX_STATE/cache
mkdir -p $cache


if [ ! -e $cache/$filename ] ; then
    temp="$filename.$$"
    echo_on
    wget -nv -O $cache/$temp "$url" || { rm -f $cache/$temp ; die "Download failed" ; }
    echo_off
    mv $cache/$temp $cache/$filename
fi


echo_on
rm -f ./$filename
cp $cache/$filename ./$filename
echo_off
