#!/bin/sh
set -eu ; set -o | grep -q pipefail && set -o pipefail
HOTBOX=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)
PATH="$HOTBOX:$HOTBOX/lib:$PATH"


export HOTBOX_TXN="$(hotbox-txn-begin $$)"
. "$HOTBOX/lib/hotbox-txn-end-on-exit.sh"
export HOTBOX_SOURCES="$(hotbox-sources-init)"


feature="${1:?expected <feature>}"


[ -f "$HOTBOX_SOURCES/$feature.system.feature.sh" ] || \
[ -f "$HOTBOX_SOURCES/$feature.user.feature.sh" ] || \
[ -f "$HOTBOX_SOURCES/$feature.run.feature.sh" ]
