#!/bin/sh
set -eu ; set -o | grep -q pipefail && set -o pipefail
HOTBOX=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)
PATH="$HOTBOX:$HOTBOX/lib:$PATH"


paths="${HOTBOX_PATH:-}"
while true ; do
    path="${paths##*:}"
    paths="${paths%:*}"
    if [ "$path" ] ; then
        echo "$path"
    fi
    if [ "$paths" = "$path" ] ; then break ; fi
done
