#!/bin/sh
set -eu ; set -o | grep -q pipefail && set -o pipefail
HOTBOX=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)
PATH="$HOTBOX:$HOTBOX/lib:$PATH"


. $HOTBOX/lib/sh.sh


path="${1:-}"
[ "$path" ] || exit 0


container_id="$(hotbox-container-id)"
[ "$container_id" ] || exit 0


get_binds() {
    docker inspect \
        $container_id \
        --format='{{range $b := .HostConfig.Binds}}{{$b}} {{end}}' \
        2>/dev/null \
        || true
}


for bind in $(get_binds) ; do
    bindext="${bind%%:*}"
    [ "$bindext" ] || continue

    bindint="${bind#*:}"
    [ "$bindint" ] || continue

    case "$path" in
        $bindint)
            ;;
        $bindint/*)
            ;;
        *)
            continue
            ;;
    esac

    echo "${bindext}${path#$bindint}"
    break
done
