#!/bin/sh
set -eu ; set -o | grep -q pipefail && set -o pipefail
HOTBOX=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)
PATH="$HOTBOX:$HOTBOX/lib:$PATH"


export HOTBOX_TXN="$(hotbox-txn-begin $$)"
. "$HOTBOX/lib/hotbox-txn-end-on-exit.sh"
. "$HOTBOX/lib/sources.sh"


feature="${1:?expected <feature>}"
command="${2:?expected <command>}"


[ -f "$HOTBOX_SOURCES/$feature.$command.feature.sh" ]
