#!/bin/sh
set -eu ; set -o | grep -q pipefail && set -o pipefail
HOTBOX=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)
PATH="$HOTBOX:$HOTBOX/lib:$PATH"


. "$HOTBOX/lib/sh.sh"
. "$HOTBOX/lib/sources.sh"


feature="${1:?expected <feature>}"
command="${2:?expected <command>}"


hotbox-feature-exists $feature || die "Feature $feature not found"


script="$HOTBOX_SOURCES/$feature.$command.feature.sh"
[ -f "$script" ] || exit 0


env HOTBOX="$HOTBOX" PATH="$HOTBOX:$HOTBOX/lib:$PATH" /bin/sh -eu $script || die "Feature script failed: $script"
