#!/bin/sh
set -eu ; set -o | grep -q pipefail && set -o pipefail
HOTBOX=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd -P)
PATH="$HOTBOX:$HOTBOX/lib:$PATH"


. $HOTBOX/lib/sh.sh


id="$(cat /proc/self/mountinfo | grep /docker/containers/ | head -n 1 || checkpipe)"
id="${id##*/docker/containers/}"
id="${id%%/*}"
[ "$id" ] || exit 1
echo $id
exit 0
