#!/bin/sh
set -eu ; set -o | grep -q pipefail && set -o pipefail
HOTBOX=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)
PATH="$HOTBOX:$HOTBOX/lib:$PATH"

. "$HOTBOX/lib/sh.sh"

pid="${1:?expected <pid>}"
id="$(uname -n).${pid}"

HOTBOX_TXN="${HOTBOX_TXN:-}"
[ "$HOTBOX_TXN" ] || exit 0
[ "$(basename "$HOTBOX_TXN")" = "$id" ] || exit 0
[ -d "$HOTBOX_TXN" ] || exit 0

heading "Ending hotbox txn $id"
echo_on
rm -rf "$HOTBOX_TXN"
echo_off
