#!/bin/sh
set -eu ; set -o | grep -q pipefail && set -o pipefail
HOTBOX=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd -P)
PATH="$HOTBOX:$HOTBOX/lib:$PATH"


. "$HOTBOX/lib/sh.sh"
export HOTBOX_TXN="$(hotbox-txn-begin $$)"
. "$HOTBOX/lib/hotbox-txn-end-on-exit.sh"
export HOTBOX_SOURCES="$(hotbox-sources-init)"


spec="${1:?expected <spec>}"
selected_key="${2:-}"

script="$HOTBOX_SOURCES/$spec.spec.sh"
[ -f "$script" ] || die "Spec $spec not found"

env HOTBOX="$HOTBOX" PATH="$HOTBOX:$HOTBOX/lib:$PATH" /bin/sh -eu "$script" | while read -r line ; do
    key="${line%%:*}"
    value="${line#*:}"

    if [ "$key" = "include" ] ; then
        hotbox-spec-read "$value" "$selected_key" || die "Error reading included $value spec"
        continue
    fi

    if [ "$selected_key" ] ; then
        if [ "$key" != "$selected_key" ] ; then
            continue
        fi

        echo "$value"
        continue
    fi

    echo "$line"
done
