#!/bin/sh
set -eu ; set -o | grep -q pipefail && set -o pipefail
HOTBOX=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)


. $HOTBOX/lib/sh.sh


location="${1:?expected <location>}"
spec="${2:?expected <spec>}"
target="${3:?expected <target>}"
selected_key="${4:-}"


script="$location/$spec.spec.sh"
test -f $script || die "Spec $spec not found"

case $target in
    machine)
        ;;
    container)
        ;;
    *)
        die "Unrecognized <target> '$target'"
esac


env HOTBOX=$HOTBOX HOTBOX_TARGET=$target /bin/sh -eu $script | while read -r line ; do
    key="${line%%:*}"
    value="${line#*:}"

    if [ "$key" = "include" ] ; then
        $HOTBOX/lib/read-spec $location $value $target $selected_key || die "Error reading included $value spec"
        continue
    fi

    if [ -n "$selected_key" ] ; then
        if [ "$key" != "$selected_key" ] ; then
            continue
        fi

        echo "$value"
        continue
    fi

    echo "$line"
done
