#!/bin/sh
set -o pipefail
set -eu
HOTBOX=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)


. $HOTBOX/lib/sh.sh


location="${1:?expected <location>}"
spec="${2:?expected <spec>}"
selected_key="${3:-}"


script="$location/$spec.spec.sh"
test -f $script || die "Spec $spec not found"


env HOTBOX=$HOTBOX /bin/sh -eu $script | while read -r line ; do
    key="${line%%:*}"
    value="${line#*:}"

    if [ "$key" = "inherit" ] ; then
        $HOTBOX/lib/read-spec $location $value $selected_key || die "Error reading inherited $value spec"
        continue
    fi

    if [ -n "$selected_key" ] ; then
        if [ "$key" != "$selected_key" ] ; then
            continue
        fi

        echo "$value"
        continue
    fi

    echo "$line"
done
