#!/bin/sh
set -eu ; set -o | grep -q pipefail && set -o pipefail
HOTBOX=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)


. "$HOTBOX/lib/sh.sh"
. "$HOTBOX/lib/sources.sh"


feature="${1:?expected <feature>}"
command="${2:?expected <command>}"


"$HOTBOX/lib/feature-exists" $feature || die "Feature $feature not found"


script="$HOTBOX_SOURCES/$feature.$command.feature.sh"
[ -f "$script" ] || exit 0


env HOTBOX="$HOTBOX" /bin/sh -eu $script || die "Feature script failed: $script"
