#!/usr/bin/env sh
set -eu
hotbox=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)


. $hotbox/lib/sh.sh


termopts=""
if [ -n "${TERM:+x}" ] ; then
    termopts="-e TERM=$TERM"
fi

dockersockopts=""
if [ -S /var/run/docker.sock ] ; then
    dockersockopts="-v /var/run/docker.sock:/var/run/docker.sock"
fi

x11sockopts=""
if [ -d /tmp/.X11-unix ] ; then
    x11sockopts="-v /tmp/.X11-unix:/tmp/.X11-unix"
fi

displayopts=""
if [ -n "${DISPLAY:+x}" ] ; then
    displayopts="-e DISPLAY=$DISPLAY"
fi

gitcredentialsopts=""
if [ -f $HOME/.git-credentials ] ; then
    gitcredentialsopts="-v $HOME/.git-credentials:/home/$(current_user)/.git-credentials"
fi


heading "Starting container"
echo_on
docker run \
    --ipc=host \
    --rm \
    -it \
    $termopts \
    $dockersockopts \
    $x11sockopts \
    $displayopts \
    $gitcredentialsopts \
    $@
echo_off
