#!/bin/sh
set -eu
HOTBOX=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)


. $HOTBOX/lib/sh.sh


test -n "${HOTBOX_USER+x}" || die "HOTBOX_USER not set"
test -n "${HOTBOX_UID+x}" || die "HOTBOX_UID not set"
test -n "${HOTBOX_GID+x}" || die "HOTBOX_GID not set"


test "$(whoami)" = "root" || die "This script must be run as root"


echo_on
addgroup --gid $HOTBOX_GID $HOTBOX_USER
adduser --disabled-password --uid $HOTBOX_UID --ingroup $HOTBOX_USER $HOTBOX_USER
echo_off
