shell="/bin/sh"
shellarg="-l"
workdir="/workspace"
features="
    $features
    container-initialise
    container-package-manager-update
    container-user
    container-docker-group
    container-hotbox
    container-workspace
    container-cook
    doas
    container-cache
"
