shell="/bin/sh"
shellarg="-l"
features="
    $features
    container-initialise
    container-package-manager-update
    container-user
    container-docker-group
    container-hotbox
    container-workspace
    container-cook
    doas
    container-cache
    container-host-x11
    container-host-docker
    container-host-git-credentials
    container-host-term
"
