#!/bin/sh
set -eu
HOTBOX=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)


. $HOTBOX/lib/sh.sh


#
# Install vim
#
if ! which vim > /dev/null ; then
    info "Vim not found on system, installing"
    case $(current_distro) in
        alpine)
            echo_on
            doas apk add vim vim-doc
            echo_off
            ;;
        ubuntu)
            echo_on
            doas env DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends vim
            echo_off
            ;;
        *)
            die "Don't know how to install vim on $current_distro os"
            ;;
    esac
fi


cd $HOME


#
# Make sure there's a .vimrc
#
if ! [ -f .vimrc ] ; then
    info "No .vimrc found, creating"
    touch .vimrc
fi


#
# Make sure .vimrc sources the hotbox vimrc
#
if ! grep -qF 'conf/vimrc' .vimrc ; then
    info "No hotbox vimrc source found in .vimrc, prepending"
    cat .vimrc > .vimrc.old
    echo "source $HOTBOX/conf/vimrc" > .vimrc
    echo >> .vimrc
    cat .vimrc.old >> .vimrc
    rm .vimrc.old
fi


#
# Install plugins
#
mkdir -p .vim/pack/hotbox/start
cd .vim/pack/hotbox/start

if ! [ -d vim-macrobsidian ] ; then
    info "Installing macrobsidian Vim plugin"
    echo_on
    git clone https://github.com/macro187/vim-macrobsidian.git
    echo_off
fi
